---
title: "Activity 1.2 - RStudio and R Markdown"
author: "Sara Harman"
date: "8/26/2019"
output: html_document
---

### Load packages

```{r load-packages, message=FALSE}
library(tidyverse) 
library(datasauRus)

```


### Exercise 1

(1,846 rows with 12 columns and 3 variables, Variables include dataset, x, and y values)

### Exercise 2


```{r plot-dino, fig.height=3, fig.width=6}
dino_data <- datasaurus_dozen %>%
  filter(dataset == "dino")

ggplot(data = dino_data, mapping = aes(x = x, y = y)) +
  geom_point()
```

And next calculate the correlation between `x` and `y` in this dataset:

```{r cor-dino}
dino_data %>%
  summarize(r = cor(x, y))
```

### Exercise 3

Plotting a star

```{r plot-star, fig.height=10, fig.width=10}
star_data <- datasaurus_dozen %>%
  filter(dataset == "star")

ggplot(data = star_data, mapping = aes(x = x, y = y)) +
  geom_point()
```
Finding the correlation coefficient

```{r cor-star}

star_data %>%
  summarize(r = cor(x, y))
```
Compared with the value of r from exercise 2, the value is extremely close in relation to one another. 
```

### Exercise 4

Plotting a circle
```
```{r plot-circle, fig.height=10, fig.width=10}

circle_data <- datasaurus_dozen %>%
  filter(dataset == "circle")

ggplot(data = circle_data, mapping = aes(x = x, y = y)) +
  geom_point()

```
```
R-value for the circle graph
```

```{r cor-circle}

circle_data %>%
  summarize(r = cor(x, y))
```

```
Again, compared with the value of the r value for the dino graph it is extremely close. 

### Exercise 5
Plotting everything
```
```{r}
ggplot(data = datasaurus_dozen, aes(x = x, y = y, color = dataset)) +
  geom_point() +
  facet_wrap(~ dataset, ncol = 3) +
  theme(legend.position = "none")
```



